### ISSUE TITLE
Library Crash

### ISSUE THREAD

**Issue by maniarali** [chronotruck/CTKFlagPhoneNumber#15] opened 2018-04-24 11:10 UTC
App crash due to this function, mostly first time when its loads.

```
func setCountryByRow(row: Int) {
		self.selectRow(row, inComponent: 0, animated: true)
		let country = countries[row]
		if let countryPickerDelegate = countryPickerDelegate {
			countryPickerDelegate.countryPhoneCodePicker(self, didSelectCountryWithName: country.name!, countryCode: country.code!, phoneCode: country.phoneCode!, flag: country.flag!)
		}
	}
```

**Comment by grifas** [comment] 2018-04-24 13:02
Thanks @maniarali to report this crash. I will add more checks and release a new pod version asap.

**Comment by grifas** [comment] 2018-04-25 07:33
@maniarali Could you try this fix on `hotfix` branch ?

**Comment by maniarali** [comment] 2018-04-26 13:14
Yes I can. I'll update soon.

**Comment by szantogab** [comment] 2018-04-28 10:51
@grifas I guess adding more checks will not solve the problem. I debugged it and the problem seems to come when we try to load the image for a given country code. The Bundle is nil at the time of the crash.

Why is that?

**Comment by szantogab** [comment] 2018-04-30 07:49
@grifas No, I'm using the built-in bundle.

**Comment by grifas** [comment] 2018-04-30 08:12
@szantogab I need more information to find the problem.
Can you describe how do you use the lib ? When and where does the crash occur?

See the example and tell me what you do different

**Comment by grifas** [comment] 2018-04-30 08:18
@szantogab Or can you provide me a branch with the issue that I can check out ? It will be easier for me to debug ;)

**Comment by grifas** [comment] 2018-04-30 08:49
@szantogab I created a new project with a fresh install of the lib, instanced the textfield in storyboard, created the `@IBOutlet` in my view controller, set the parent view controller in the `viewDidLoad` build and launch on a simulator and I have no crash :/

Please provide me a branch with your code where the issue occurs.

**Comment by szantogab** [comment] 2018-04-30 09:04
@grifas Have you tried to test this code multiple times? It works correctly for me 90% of the time.

**Comment by grifas** [comment] 2018-04-30 09:06
@szantogab Yes I tried this code multiple times. It works correctly for me 100% of the time.

Please provide me a branch with your code where the issue occurs.

**Comment by maniarali** [comment] 2018-04-30 12:02
I am also using default bundle. I also feel the issue is because bundle doesn't load, however with hotfix branch the problem doesn't occurring now.

I am not sure flag is showing or not. 

I would suggest test on main branch and in your new project initialise with wrong number, at first you'll get a crash.

like : `self.phoneNumberText.set(phoneNumber:  "Some wrong number")`

**Comment by grifas** [comment] 2018-04-30 12:17
@maniarali I got no crash :/

Please provide me a branch with your code where the issue occurs.

**Comment by grifas** [comment] 2018-04-30 12:39
@szantogab No, I created a new project with fresh install of the CTKFlagPhoneNumber pod via Cocoapods.

I'm sorry I don't have time to see your project. Take the time to reproduce the issue in a new fresh project. If you can't reproduce it, I think the problem comes from your project.

**Comment by khushDesai** [comment] 2018-05-16 08:32
@maniarali @szantogab @Arasthel @maffpool  Have you Found any Solution?

**Comment by grifas** [comment] 2018-05-16 08:56
@khushDesai Can you print the country object at the crash and paste it here please ?

**Comment by khushDesai** [comment] 2018-05-16 10:26
![screen shot 2018-05-16 at 3 56 19 pm](https://user-images.githubusercontent.com/29880773/40111843-b6ef703e-5921-11e8-97e8-e77b0a1716d2.png)
@grifas  Please check this

**Comment by grifas** [comment] 2018-05-16 11:42
@khushDesai @maniarali @szantogab @Arasthel I think I found the issue. I fixed it in `hotfix` branch. Could you test it ? Thanks

**Comment by khushDesai** [comment] 2018-05-16 11:53
![screen shot 2018-05-16 at 5 22 39 pm](https://user-images.githubusercontent.com/29880773/40115358-c9ea486a-592d-11e8-8474-62577e2b00cf.png)

@grifas Please Check this

**Comment by maniarali** [comment] 2018-05-16 12:43
I have tested your latest code. It's seems like you have solved the issue. I need some more time to verify it. @khushDesai @szantogab what are your reviews ?

**Comment by khushDesai** [comment] 2018-05-17 04:49
@grifas Should i install Pod of hotfix branch?

**Comment by khushDesai** [comment] 2018-05-17 05:38
@grifas after installing pods from hotfix i am getting empty view :(

**Comment by maniarali** [comment] 2018-05-17 06:02
Can you try out with commit tag ?

> pod 'CTKFlagPhoneNumber', :git => 'https://github.com/chronotruck/CTKFlagPhoneNumber.git', :branch => 'hotfix', :commit => 'fd6987c'

**Comment by khushDesai** [comment] 2018-05-17 06:10
@maniarali  I am getting this after installing pods with commit 
![img_8274](https://user-images.githubusercontent.com/29880773/40159485-2213cce8-59c7-11e8-9e2a-c3596dc85f72.jpg)

**Comment by grifas** [comment] 2018-05-17 07:57
@khushDesai Could you add breakpoints like on this picture in the country model, run and see if it enters in one of these conditions (line 15 or 17) ?

<img width="783" alt="screen shot 2018-05-17 at 09 54 24" src="https://user-images.githubusercontent.com/9267969/40164004-a79cfc2c-59b8-11e8-86c8-c7b3027436cc.png">

**Comment by khushDesai** [comment] 2018-05-17 08:05
![screen shot 2018-05-17 at 1 34 25 pm](https://user-images.githubusercontent.com/29880773/40164413-12ab92bc-59d7-11e8-9a10-7b19aef740cb.png)
@grifas Please check this

**Comment by grifas** [comment] 2018-05-17 08:07
@khushDesai Ok this means it doesn't find the bundle flags xcassets. Have you the FlagKit.xcassets in Resources repository in the CTKFlagPhoneNumber pod repository. Is it empty ?

**Comment by khushDesai** [comment] 2018-05-17 08:10
@grifas http://prntscr.com/jiyiln I have FlagKit.xcassets in Resource repository

**Comment by grifas** [comment] 2018-05-17 08:16
@khushDesai Could you print the `Bundle.FlagIcons` at the breakpoint in country model ?

**Comment by khushDesai** [comment] 2018-05-17 08:19
![screen shot 2018-05-17 at 1 48 40 pm](https://user-images.githubusercontent.com/29880773/40165212-09531cb0-59d9-11e8-8d89-8eadddb13eae.png)
@grifas  Please check this!

**Comment by khushDesai** [comment] 2018-05-17 08:39
@grifas Is there any solution? Otherwise i will change Library because  i am waiting for solution.

**Comment by grifas** [comment] 2018-05-17 08:43
@khushDesai I made an update. Could you retry to pod install with the commit `d3fbd19 `

`pod 'CTKFlagPhoneNumber', :git => 'https://github.com/chronotruck/CTKFlagPhoneNumber.git', :branch => 'hotfix', :commit => 'd3fbd19'`

**Comment by khushDesai** [comment] 2018-05-17 08:55
Its still not working

**Comment by grifas** [comment] 2018-05-17 09:00
@khushDesai I have no solution for this time. May be you can provide me a new project with this issue ? It will be easier for me to debug.

@maniarali @szantogab @Arasthel Is it good for you ?

**Comment by maniarali** [comment] 2018-05-17 09:29
@grifas I am not facing this issue since your second last commit. 
@khushDesai can u please **remove this pod** completely, then **clean** your project and delete your **DerivedData** and then reinstall pod with hotfix branch, also **delete your app** from device. 

Hopefully it will work.

**Comment by grifas** [comment] 2018-05-17 09:34
I close this issue because there is no longer crash. @khushDesai after doing what @maniarali suggests you, if you have always your bug, open a new issue.

Thanks guys to use this lib ;)

**Closed by grifas** 2018-05-17 09:34 UTC
Labels: bug
